[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = { Cache-Control = "no-cache" }

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  headers = { Cache-Control = "public, max-age=31536000, immutable" }
